"""Reproduction tests: bit-identical determinism + fingerprint match.

The fingerprint (tests/expected.json, generated by tools/make_refs.py) pins
exact outputs of fast deterministic computations spanning the stack. Any
unintentional behavior change fails loudly here. Regenerate deliberately via
tools/make_refs.py after INTENDED changes, and review the diff.

Run:  pytest tests/ -q
Cross-process check: run twice with different PYTHONHASHSEED values.
"""
import json
import random
from pathlib import Path

import flywheel_sim as base
import flywheel_harness3 as h3
import flywheel_pkg9 as p9

ROOT = Path(__file__).resolve().parent.parent
EXPECTED = json.load(open(ROOT / "tests" / "expected.json"))


def _canon(o):
    return json.loads(json.dumps(o, sort_keys=True, default=str))


def test_generate_batch_deterministic():
    sm = base.make_sm0()
    a = base.generate_batch(sm, 0, 3, 20260907)
    b = base.generate_batch(base.make_sm0(), 0, 3, 20260907)
    assert _canon(a) == _canon(b)


def test_bank_heads_match():
    assert _canon(p9.make_bank(777, 16, "D")[0]) == _canon(EXPECTED["bank_head"])
    assert _canon(p9.make_bank(31337, 8, "Q")[0]) == _canon(EXPECTED["probe_head"])


def test_scorer_values_match():
    art = {"problem_id": "P07", "problem_text": "", "cot": ["Next, 82 + 91 + 77 + 90 = 340."],
           "final_line": "Final: 85", "final_answer": 85, "ground_truth": 85}
    assert _canon(base.rule_evaluate(art)) == _canon(EXPECTED["legacy_P07"])
    assert _canon(h3.rule_evaluate_v3(dict(art), "fixed")) == _canon(EXPECTED["fixed_P07"])


def test_golden_and_calibration_match():
    import flywheel_harness as h1
    gold = h1.make_golden_set()
    assert [a["rule_score"] for a in gold] == EXPECTED["golden_rule"]
    jrng = random.Random(777)
    sm0 = base.make_sm0()
    raw = [h1._blind_raw(a["rule_score"], sm0, jrng) for a in gold]
    assert list(h1._fit_affine(raw, [a["rule_score"] for a in gold])) == EXPECTED["golden_calib"]


def test_mini_flywheel_match():
    sm = base.make_sm0()
    a0 = base.generate_batch(sm, 0, 3, 20260907)
    base.evaluate_batch(a0, None, 1.0, 11)
    kept = base.select_kept(a0, thresh=70.0)
    sm1 = base.train_next_sm("SM-1", [sm], kept, [0], temp_override=0.85, lesson="fp")
    a1 = base.generate_batch(sm1, 1, 3, 20260907 + 100)
    base.evaluate_batch(a1, None, 1.0, 18)
    got = {"r0": base.round_metrics(a0), "r1": base.round_metrics(a1),
           "kept0": len(kept), "sm1_params": sm1.params}
    assert _canon(got) == _canon(EXPECTED["mini"])
